"""add sync cursor + last_synced_at to plaid_items

Revision ID: edd936176def
Revises: 1cdb2a80e301
Create Date: 2026-05-03 02:16:41.245166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edd936176def'
down_revision: Union[str, None] = '1cdb2a80e301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('transactions_cursor', sa.String(length=512), nullable=True))
    op.add_column('plaid_items', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_items', 'last_synced_at')
    op.drop_column('plaid_items', 'transactions_cursor')
    # ### end Alembic commands ###
